name: Epic Network
description: Epic Network Mobile Mining App
full_description: 'EPIC Network is an all-in-one decentralized<br>
<br>cryptocurrency platform with huge plans! 
<br>EPIC is fairly distributed, eco-friendly and
<br>consumes minimal battery power. EPIC is fair 
<br>and valuable to everyone.'
android: https://play.google.com/store/apps/details?id=com.epicchain.epicnetwork
iOS: https://play.google.com/store/apps/details?id=com.epicchain.epicnetwork
web: https://mineepic.com/
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
  - 5.png
producthunt: https://play.google.com/store/apps/details?id=com.epicchain.epicnetwork
companies:
  - url: https://play.google.com/store/apps/details?id=com.epicchain.epicnetwork
    image: androidpolice.png
  - url: https://play.google.com/store/apps/details?id=com.epicchain.epicnetwork
    image: producthunt.png
