name: Epic Network
description: Epic Network Mobile Mining App
full_description: 'EPIC Network is an all-in-one decentralized<br>
<br>cryptocurrency platform with huge plans! 
<br>EPIC is fairly distributed, eco-friendly and
<br>consumes minimal battery power. EPIC is fair 
<br>and valuable to everyone.'
android: https://telegra.ph/Replace-this-link-07-23
iOS: https://telegra.ph/Replace-this-link-07-23
web: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
producthunt: https://telegra.ph/Replace-this-link-07-23
companies:
  - url: https://telegra.ph/Replace-this-link-07-23
    image: androidpolice.png
  - url: https://telegra.ph/Replace-this-link-07-23
    image: producthunt.png
